export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const CREATE_VACANCY_SUCCESS = "CREATE_VACANCY_SUCCESS";
export const EDIT_VACANCY_SUCCESS = "EDIT_VACANCY_SUCCESS";
export const GET_VACANCIES_SUCCESS = "GET_VACANCIES_SUCCESS";

export const GET_SPECIALTIES = "GET_SPECIALTIES";
export const GET_INDUSTIRES = "GET_INDUSTRIES";
export const GET_FUNCTIONS = "GET_FUNCTIONS";